-- Organograma de Tecnologia (seed estrutural da aplicação)
-- Fonte: data/organograma_tecnologia.csv

CREATE TABLE IF NOT EXISTS tech_organogram (
  email TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  role_title TEXT NOT NULL DEFAULT '',
  leader_name TEXT NOT NULL DEFAULT '',
  leader_email TEXT NOT NULL DEFAULT '',
  tribe TEXT NOT NULL DEFAULT '',
  legacy_manager_name TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_tech_organogram_name_lower
  ON tech_organogram (lower(name));

CREATE INDEX IF NOT EXISTS idx_tech_organogram_tribe
  ON tech_organogram (tribe);

CREATE INDEX IF NOT EXISTS idx_tech_organogram_leader_email
  ON tech_organogram (leader_email);

-- Substitui carga anterior (organograma empresa-wide) pelo de tecnologia
DELETE FROM tech_organogram;

INSERT INTO tech_organogram (
  email, name, role_title, leader_name, leader_email, tribe, legacy_manager_name
) VALUES
  ('fernando.cardia@gran.com', 'Fernando Coelho de Sousa Cardia', 'SOFTWARE ENGINEER III', 'Alef Rogers Molar Beserra', 'alef.beserra@gran.com', 'Payments', 'Alef Rogers Molar Beserra'),
  ('guilherme.cardoso@gran.com', 'Guilherme Cesar Cardoso', 'SOFTWARE ENGINEER II', 'Alef Rogers Molar Beserra', 'alef.beserra@gran.com', 'Payments', 'Alef Rogers Molar Beserra'),
  ('marcelo.fortes@gran.com', 'Marcelo Rodrigues Fortes', 'SOFTWARE ENGINEER II', 'Alef Rogers Molar Beserra', 'alef.beserra@gran.com', 'Payments', 'Alef Rogers Molar Beserra'),
  ('natan.santana@gran.com', 'Natan Tavares Santana', 'SOFTWARE ENGINEER I', 'Alef Rogers Molar Beserra', 'alef.beserra@gran.com', 'Payments', 'Alef Rogers Molar Beserra'),
  ('pedro.avezzani@gran.com', 'Pedro Henrique Ferreira Avezzani', 'SOFTWARE ENGINEER III', 'Alef Rogers Molar Beserra', 'alef.beserra@gran.com', 'Payments', 'Alef Rogers Molar Beserra'),
  ('sabrina.silva@gran.com', 'Sabrina Rocha De Souza Silva', 'QA ANALYST III', 'Alef Rogers Molar Beserra', 'alef.beserra@gran.com', 'Payments', 'Alef Rogers Molar Beserra'),
  ('barbara.moura@gran.com', 'Barbara Luisa Magalhaes Soares De Moura', 'SRE I', 'Allyni Fabiola Cesar Costa', 'allyni.costa@gran.com', 'DevOps', 'Murilo Augusto Peres'),
  ('edson.junior@gran.com', 'Edson da Conceicao Junior', 'ANALISTA INFRAESTRUTURA DEVOPS PL', 'Allyni Fabiola Cesar Costa', 'allyni.costa@gran.com', 'DevOps', 'Murilo Augusto Peres'),
  ('eric.pereira@gran.com', 'Eric Fernandes Pereira', 'SRE II', 'Allyni Fabiola Cesar Costa', 'allyni.costa@gran.com', 'DevOps', 'Allyni Fabiola Cesar Costa'),
  ('leonardo.vaz@gran.com', 'Leonardo Tavares Simoes Vaz', 'SRE II', 'Allyni Fabiola Cesar Costa', 'allyni.costa@gran.com', 'DevOps', 'Allyni Fabiola Cesar Costa'),
  ('igor.sarmento@gran.com', 'Igor Gomes Sarmento', 'SOFTWARE ENGINEER II', 'Daniel Dos Rios Dias Duarte', 'daniel.duarte@gran.com', 'Preparatórios', 'Diogo Luis Da Silva Montanari'),
  ('charllys.lima@gran.com', 'Charllys Lima', 'Não informado no diretório', 'Daniel Rios Dias Duarte', 'daniel.duarte@gran.com', '', ''),
  ('daniel.oliveira@gran.com', 'Daniel Vaz de Oliveira', 'SOFTWARE ENGINEER II', 'Daniel Rios Dias Duarte', 'daniel.duarte@gran.com', 'Preparatórios', 'Daniel Dos Rios Dias Duarte'),
  ('diego.lourenco@gran.com', 'Diego da Silva Lourenco', 'SOFTWARE ENGINEER III', 'Daniel Rios Dias Duarte', 'daniel.duarte@gran.com', 'Preparatórios', 'Daniel Dos Rios Dias Duarte'),
  ('joao.queiroz@gran.com', 'Joao Pedro Silva De Queiroz', 'SOFTWARE ENGINEER ASSOCIATE', 'Daniel Rios Dias Duarte', 'daniel.duarte@gran.com', 'Preparatórios', 'Daniel Dos Rios Dias Duarte'),
  ('samuel.santos@gran.com', 'Samuel Souza Santos', 'SOFTWARE ENGINEER III', 'Daniel Rios Dias Duarte', 'daniel.duarte@gran.com', 'Preparatórios', 'Daniel Dos Rios Dias Duarte'),
  ('arthur.fakhouri@gran.com', 'Arthur Georges Fakhouri', 'SOFTWARE ENGINEER I', 'Diego De Melo Barbosa', 'diego.barbosa@gran.com', 'Growth', 'Diego De Melo Barbosa'),
  ('beatriz.costa@gran.com', 'Beatriz Vitoria Ramos Costa', 'ESTAGIARIO', 'Diego De Melo Barbosa', 'diego.barbosa@gran.com', 'Growth', 'Diego De Melo Barbosa'),
  ('carlos.goncalves@gran.com', 'Carlos Artur Neubert Goncalves', 'SOFTWARE ENGINEER III', 'Diego De Melo Barbosa', 'diego.barbosa@gran.com', 'Growth', 'Diego De Melo Barbosa'),
  ('igor.silva@gran.com', 'Igor Dos Santos Goncalves Silva', 'SOFTWARE ENGINEER I', 'Diego De Melo Barbosa', 'diego.barbosa@gran.com', 'Growth', 'Diego De Melo Barbosa'),
  ('lucas.cherigath@gran.com', 'Lucas Cardoso Cherigath', 'SOFTWARE ENGINEER III', 'Diego De Melo Barbosa', 'diego.barbosa@gran.com', 'Growth', 'Diego De Melo Barbosa'),
  ('luiz.correa@gran.com', 'Luiz Eduardo Correa', 'Não informado no diretório', 'Diego De Melo Barbosa', 'diego.barbosa@gran.com', '', ''),
  ('paulo.lima@gran.com', 'Paulo Bruny Araujo Lima', 'SOFTWARE ENGINEER II', 'Diego De Melo Barbosa', 'diego.barbosa@gran.com', 'Growth', 'Diego De Melo Barbosa'),
  ('paulo.pereira@gran.com', 'Paulo Henrique Mendes Pereira', 'SOFTWARE ENGINEER II', 'Diego De Melo Barbosa', 'diego.barbosa@gran.com', 'Growth', 'Diego De Melo Barbosa'),
  ('ediano.guimaraes@gran.com', 'Ediano Gama Guimaraes', 'SOFTWARE ENGINEER III', 'Erick Francis Matias Oliveira', 'erick.oliveira@gran.com', 'Backoffice', 'Erick Francis Matias Oliveira'),
  ('gabriel.cavalcante@gran.com', 'Gabriel Carlos Cavalcante', 'SOFTWARE ENGINEER II', 'Erick Francis Matias Oliveira', 'erick.oliveira@gran.com', 'Backoffice', 'Erick Francis Matias Oliveira'),
  ('willian.moura@gran.com', 'Willian Santos Moura', 'SOFTWARE ENGINEER II', 'Erick Francis Matias Oliveira', 'erick.oliveira@gran.com', 'Backoffice', 'Erick Francis Matias Oliveira'),
  ('jonatas.oliveira@gran.com', 'Jonatas Miler De Oliveira', 'DESENVOLVEDOR FULLSTACK PL', 'Fabiano Rodrigues Ugulino', 'fabiano.ugulino@gran.com', 'Backoffice', 'Fabiano Rodrigues Ugulino'),
  ('marcelo.hoffmeister@gran.com', 'Marcelo Henrique Hoffmeister', 'SOFTWARE ENGINEER III', 'Fabiano Rodrigues Ugulino', 'fabiano.ugulino@gran.com', 'Backoffice', 'Fabiano Rodrigues Ugulino'),
  ('matheus.carvalho@gran.com', 'Matheus Teofilo De Carvalho', 'SOFTWARE ENGINEER I', 'Fabiano Rodrigues Ugulino', 'fabiano.ugulino@gran.com', 'Backoffice', 'Fabiano Rodrigues Ugulino'),
  ('rafaela.queiroz@gran.com', 'Rafaela Da Mota Queiroz', 'SOFTWARE ENGINEER I', 'Fabiano Rodrigues Ugulino', 'fabiano.ugulino@gran.com', 'Backoffice', 'Fabiano Rodrigues Ugulino'),
  ('wesley.santos@gran.com', 'Wesley Rogerio Amorim dos Santos', 'STAFF IT SUPPORT', 'Fabiano Rodrigues Ugulino', 'fabiano.ugulino@gran.com', 'Backoffice', 'Fabiano Rodrigues Ugulino'),
  ('danilo.sousa@gran.com', 'Danilo de Sousa', 'STAFF SOFTWARE ENGINEER', 'Fernando Ferreira Da Silva', 'fernando.silva@gran.com', 'IA', 'Fernando Ferreira Da Silva'),
  ('joao.freitas@gran.com', 'Joao Luiz Pereira De Freitas', 'SOFTWARE ENGINEER II', 'Fernando Ferreira Da Silva', 'fernando.silva@gran.com', 'IA', 'Fernando Ferreira Da Silva'),
  ('luciana.ferreira@gran.com', 'Luciana Reynaud Ferreira', 'IA GOVERNANCE ANALYST II', 'Fernando Ferreira Da Silva', 'fernando.silva@gran.com', 'IA', 'Fernando Ferreira Da Silva'),
  ('samuel.lima@gran.com', 'Samuel De Morais Lima', 'SOFTWARE ENGINEER I', 'Fernando Ferreira Da Silva', 'fernando.silva@gran.com', 'IA', 'Fernando Ferreira Da Silva'),
  ('vitor.alves@gran.com', 'Vitor Alves', 'Não informado no diretório', 'Fernando Ferreira Da Silva', 'fernando.silva@gran.com', '', ''),
  ('wanderson.fontes@gran.com', 'Wanderson Fontes', 'DESENVOLVEDOR BACK-END PL', 'Fernando Ferreira Da Silva', 'fernando.silva@gran.com', '', ''),
  ('filippe.rocha@gran.com', 'Filippe Jobim Rocha', 'DATA ANALYST III', 'Gabriel Costa Abreu', 'gabriel.abreu@gran.com', 'Dados', 'Gabriel Costa Abreu'),
  ('leandro.garcia@gran.com', 'Leandro Alves Garcia', 'DATA ANALYST II', 'Gabriel Costa Abreu', 'gabriel.abreu@gran.com', 'Dados', 'Gabriel Costa Abreu'),
  ('rafael.alves@gran.com', 'Rafael Jose Alves', 'DATA ANALYST III', 'Gabriel Costa Abreu', 'gabriel.abreu@gran.com', 'Dados', 'Gabriel Costa Abreu'),
  ('alex.moura@gran.com', 'Alex Serafim de Moura', 'Não informado no diretório', 'Gleyson da Silva Carvalho', 'gleyson.carvalho@gran.com', '', ''),
  ('davi.luna@gran.com', 'Davi Soares Luna', 'ASSISTENTE SUPORTE TECNICO', 'Gleyson da Silva Carvalho', 'gleyson.carvalho@gran.com', 'Cyber Security', 'Gleyson Da Silva Carvalho'),
  ('gustavo.flores@gran.com', 'Gustavo Henrique de Franca Flores', 'AUXILIAR SUPORTE TECNICO', 'Gleyson da Silva Carvalho', 'gleyson.carvalho@gran.com', 'Cyber Security', 'Gleyson Da Silva Carvalho'),
  ('joel.silva@gran.com', 'Joel Correia da Silva', 'IT SUPPORT ASSOCIATE', 'Gleyson da Silva Carvalho', 'gleyson.carvalho@gran.com', 'Cyber Security', 'Gleyson Da Silva Carvalho'),
  ('kevin.ribeiro@gran.com', 'Kevin Oliveira Ribeiro', 'ESTAGIARIO', 'Gleyson da Silva Carvalho', 'gleyson.carvalho@gran.com', 'Cyber Security', 'Gleyson Da Silva Carvalho'),
  ('miguel.barros@gran.com', 'Miguel Dos Santos Alves Barros', 'AUXILIAR SUPORTE TECNICO', 'Gleyson da Silva Carvalho', 'gleyson.carvalho@gran.com', 'Cyber Security', 'Gleyson Da Silva Carvalho'),
  ('beatriz.cantilho@gran.com', 'Beatriz Cirilo Cantilho', 'SOFTWARE ENGINEER III', 'Gustavo Fernandes da Guarda', 'gustavo.guarda@gran.com', 'Preparatórios', 'Gustavo Fernandes Da Guarda'),
  ('danilo.melo@gran.com', 'Danilo Schmidt de Melo', 'SOFTWARE ENGINEER II', 'Gustavo Fernandes da Guarda', 'gustavo.guarda@gran.com', 'Preparatórios', 'Gustavo Fernandes Da Guarda'),
  ('david.santos@gran.com', 'David Martins dos Santos', 'SOFTWARE ENGINEER II', 'Gustavo Fernandes Da Guarda', 'gustavo.guarda@gran.com', 'Preparatórios', 'Diogo Luis Da Silva Montanari'),
  ('erick.reis@gran.com', 'Erick Antonio Correa Dos Reis', 'SOFTWARE ENGINEER II', 'Gustavo Fernandes Da Guarda', 'gustavo.guarda@gran.com', 'Preparatórios', 'Diogo Luis Da Silva Montanari'),
  ('fernando.ferreira@gran.com', 'Fernando de Araujo Ferreira', 'SOFTWARE ENGINEER II', 'Gustavo Fernandes Da Guarda', 'gustavo.guarda@gran.com', 'Preparatórios', 'Diogo Luis Da Silva Montanari'),
  ('fernao.lara@gran.com', 'Fernao Lopes Ginez De Lara', 'SOFTWARE ENGINEER II', 'Gustavo Fernandes da Guarda', 'gustavo.guarda@gran.com', 'Preparatórios', 'Gustavo Fernandes Da Guarda'),
  ('marco.santos@gran.com', 'Marco Vinicio Belmont Santos', 'DESENVOLVEDOR FULLSTACK PL', 'Gustavo Fernandes da Guarda', 'gustavo.guarda@gran.com', 'Preparatórios', 'Gustavo Fernandes Da Guarda'),
  ('alex.kato@gran.com', 'Alex Takao Kato', 'STAFF SRE', 'Henrique Lages Repulho', 'henrique.repulho@gran.com', 'DevOps', 'Roger Luiz Pereira'),
  ('alexandre.bocato@gran.com', 'Alexandre Bocato', 'Não informado no diretório', 'Henrique Lages Repulho', 'henrique.repulho@gran.com', '', ''),
  ('cleber.santos@gran.com', 'Cleber Costa dos Santos', 'STAFF ENTERPRISE ARCHITECT', 'Henrique Lages Repulho', 'henrique.repulho@gran.com', 'DevOps', 'Henrique Lages Repulho'),
  ('elton.silva@gran.com', 'Elton Manoel da Silva', 'STAFF ENTERPRISE ARCHITECT', 'Henrique Lages Repulho', 'henrique.repulho@gran.com', 'DevOps', 'Henrique Lages Repulho'),
  ('flavia.bortoletto@gran.com', 'Flavia Ribeiro Bortoletto', 'SRE II', 'Henrique Lages Repulho', 'henrique.repulho@gran.com', 'DevOps', 'Allyni Fabiola Cesar Costa'),
  ('rafael.ferreira@gran.com', 'Rafael Ferreira', 'CLOUD ENGINEER III', 'Henrique Lages Repulho', 'henrique.repulho@gran.com', 'DevOps', 'Murilo Augusto Peres'),
  ('adriano.fernandes@gran.com', 'Adriano Vinicius Leite Fernandes', 'NO CODE DEVELOPER I', 'Joilson Thadeu Marques de Souza', 'joilson.souza@gran.com', 'Backoffice', 'Danilo Moreira Soares'),
  ('anglesson.araujo@gran.com', 'Anglesson dos Santos Araujo', 'SOFTWARE ENGINEER II', 'Joilson Thadeu Marques de Souza', 'joilson.souza@gran.com', 'Backoffice', 'Joilson Thadeu Marques De Souza'),
  ('bianca.ramal@gran.com', 'Bianca de Souza Ramal', 'SOFTWARE ENGINEER I', 'Joilson Thadeu Marques de Souza', 'joilson.souza@gran.com', 'Backoffice', 'Joilson Thadeu Marques De Souza'),
  ('felipe.carvalho@gran.com', 'Felipe De Oliveira Carvalho', 'SOFTWARE ENGINEER III', 'Joilson Thadeu Marques de Souza', 'joilson.souza@gran.com', 'Backoffice', 'Joilson Thadeu Marques De Souza'),
  ('iago.guedes@gran.com', 'Iago Oliveira Guedes', 'QA ANALYST III', 'Joilson Thadeu Marques de Souza', 'joilson.souza@gran.com', 'Backoffice', 'Joilson Thadeu Marques De Souza'),
  ('joao.lago@gran.com', 'Joao Victor Ribeiro Lago', 'ANALISTA ADMINISTRATIVO PL', 'Joilson Thadeu Marques De Souza', 'joilson.souza@gran.com', 'Backoffice', 'Danilo Moreira Soares'),
  ('sara.aviz@gran.com', 'Sara Caroline Carrera de Aviz', 'ESTAGIARIO', 'Joilson Thadeu Marques de Souza', 'joilson.souza@gran.com', 'Backoffice', 'Joilson Thadeu Marques De Souza'),
  ('augusto.santos@gran.com', 'Augusto Cezar de Sousa Santos', 'SOFTWARE ENGINEER I', 'Jordan Fernandes Aguiar da Silva', 'jordan.silva@gran.com', 'Preparatórios', 'Jordan Fernandes Aguiar Da Silva'),
  ('bruno.batista@gran.com', 'Bruno Kaike do Nascimento Batista', 'ESTAGIARIO', 'Jordan Fernandes Aguiar da Silva', 'jordan.silva@gran.com', 'Preparatórios', 'Jordan Fernandes Aguiar Da Silva'),
  ('gustavo.almeida@gran.com', 'Gustavo Henrique Lima Mendes de Almeida', 'ESTAGIARIO', 'Jordan Fernandes Aguiar da Silva', 'jordan.silva@gran.com', 'Preparatórios', 'Jordan Fernandes Aguiar Da Silva'),
  ('jonas.lopes@gran.com', 'Jonas de Albuquerque Lopes', 'SOFTWARE ENGINEER II', 'Jordan Fernandes Aguiar da Silva', 'jordan.silva@gran.com', 'Preparatórios', 'Jordan Fernandes Aguiar Da Silva'),
  ('michel.camatta@gran.com', 'Michel Guarieiro Camatta', 'SOFTWARE ENGINEER II', 'Jordan Fernandes Aguiar da Silva', 'jordan.silva@gran.com', 'Preparatórios', 'Jordan Fernandes Aguiar Da Silva'),
  ('pedro.fonseca@gran.com', 'Pedro Henrique Camara Fonseca', 'SOFTWARE ENGINEER II', 'Jordan Fernandes Aguiar da Silva', 'jordan.silva@gran.com', 'Preparatórios', 'Jordan Fernandes Aguiar Da Silva'),
  ('david.diniz@gran.com', 'David Sue Alves Diniz', 'STAFF SOFTWARE ENGINEER', 'Leonardo Pacheco', 'leonardo.pacheco@gran.com', 'Backoffice', 'Leonardo Pacheco Borges'),
  ('erick.oliveira@gran.com', 'Erick Francis Matias Oliveira', 'DESENVOLVEDOR FULLSTACK SR', 'Leonardo Pacheco', 'leonardo.pacheco@gran.com', 'Backoffice', 'Leonardo Pacheco Borges'),
  ('fabiano.ugulino@gran.com', 'Fabiano Rodrigues Ugulino', 'COORDENADOR DESENVOLVIMENTO SOFTWARE', 'Leonardo Pacheco', 'leonardo.pacheco@gran.com', 'Backoffice', 'Leonardo Pacheco Borges'),
  ('joilson.souza@gran.com', 'Joilson Thadeu Marques de Souza', 'TECH MANAGER', 'Leonardo Pacheco', 'leonardo.pacheco@gran.com', 'Backoffice', 'Leonardo Pacheco Borges'),
  ('daniel.duarte@gran.com', 'Daniel Rios Dias Duarte', 'Não informado no diretório', 'Lindalberto Rufino Vales Campelo Filho', 'lindalberto.filho@gran.com', '', ''),
  ('gustavo.guarda@gran.com', 'Gustavo Fernandes da Guarda', 'TECH MANAGER', 'Lindalberto Rufino Vales Campelo Filho', 'lindalberto.filho@gran.com', 'Preparatórios', 'Lindalberto Rufino Vales Campelo Filho'),
  ('jordan.silva@gran.com', 'Jordan Fernandes Aguiar da Silva', 'TECH MANAGER', 'Lindalberto Rufino Vales Campelo Filho', 'lindalberto.filho@gran.com', 'Preparatórios', 'Lindalberto Rufino Vales Campelo Filho'),
  ('luis.arantes@gran.com', 'Luis Fernando Meireles Arantes', 'Não informado no diretório', 'Lindalberto Rufino Vales Campelo Filho', 'lindalberto.filho@gran.com', 'Preparatórios', ''),
  ('pedro.oliveira@gran.com', 'Pedro Philipe Alves de Oliveira', 'STAFF SOFTWARE ENGINEER', 'Lindalberto Rufino Vales Campelo Filho', 'lindalberto.filho@gran.com', 'Preparatórios', 'Lindalberto Rufino Vales Campelo Filho'),
  ('rafael.bruno@gran.com', 'Rafael Bruno De Sousa Oliveira', 'STAFF SOFTWARE ENGINEER', 'Lindalberto Rufino Vales Campelo Filho', 'lindalberto.filho@gran.com', 'Preparatórios', 'Lindalberto Rufino Vales Campelo Filho'),
  ('victor.silva@gran.com', 'Victor Bruno De Oliveira Silva', 'STAFF SOFTWARE ENGINEER', 'Lindalberto Rufino Vales Campelo Filho', 'lindalberto.filho@gran.com', 'Preparatórios', 'Lindalberto Rufino Vales Campelo Filho'),
  ('allan.ribeiro@gran.com', 'Allan Alves Ribeiro', 'SOFTWARE ENGINEER II', 'Luis Fernando Meireles Arantes', 'luis.arantes@gran.com', 'Preparatórios', 'Luis Fernando Meireles Arantes'),
  ('ana.rodrigues@gran.com', 'Ana Clara Ribeiro Rodrigues da Cunha', 'ESTAGIARIO', 'Luis Fernando Meireles Arantes', 'luis.arantes@gran.com', 'Preparatórios', 'Vitor Martinelli Braga'),
  ('diego.bitencourt@gran.com', 'Diego de Souza Bitencourt', 'ESTAGIARIO', 'Luis Fernando Meireles Arantes', 'luis.arantes@gran.com', 'Preparatórios', 'Luis Fernando Meireles Arantes'),
  ('hygor.santos@gran.com', 'Hygor Silva Nunes Dos Santos', 'SOFTWARE ENGINEER II', 'Luis Fernando Meireles Arantes', 'luis.arantes@gran.com', 'Preparatórios', 'Vitor Martinelli Braga'),
  ('lizis.santos@gran.com', 'Lizis Bianca Da Silva Santos', 'SOFTWARE ENGINEER ASSOCIATE', 'Luis Fernando Meireles Arantes', 'luis.arantes@gran.com', 'Preparatórios', 'Vitor Martinelli Braga'),
  ('nicolas.rocha@gran.com', 'Nicolas Kenji Yamada Rocha', 'SOFTWARE ENGINEER I', 'Luis Fernando Meireles Arantes', 'luis.arantes@gran.com', 'Preparatórios', 'Luis Fernando Meireles Arantes'),
  ('italo.ferreira@gran.com', 'Italo Andre Da Conceicao Ferreira', 'SOFTWARE ENGINEER II', 'Luiz Inacio De Araujo Correa', 'luiz.araujo@gran.com', 'Payments', 'Luiz Inacio De Araujo Correa'),
  ('kayo.silva@gran.com', 'Kayo Leandro Oliveira Silva', 'SOFTWARE ENGINEER III', 'Luiz Inacio De Araujo Correa', 'luiz.araujo@gran.com', 'Payments', 'Luiz Inacio De Araujo Correa'),
  ('sidney.alves@gran.com', 'Sidney Sampaio Alves', 'SOFTWARE ENGINEER II', 'Luiz Inacio De Araujo Correa', 'luiz.araujo@gran.com', 'Payments', 'Luiz Inacio De Araujo Correa'),
  ('alef.beserra@gran.com', 'Alef Rogers Molar Beserra', 'TECH MANAGER', 'Manoel Roberto Aguirre de Almeida', 'manoel.almeida@gran.com', 'Payments', 'Manoel Roberto Aguirre De Almeida'),
  ('fernando.silva@gran.com', 'Fernando Ferreira Da Silva', 'Engineering Manager', 'Manoel Roberto Aguirre de Almeida', 'manoel.almeida@gran.com', 'IA', 'Manoel Roberto Aguirre De Almeida'),
  ('leonardo.pacheco@gran.com', 'Leonardo Pacheco', 'Engineering Manager', 'Manoel Roberto Aguirre de Almeida', 'manoel.almeida@gran.com', 'Backoffice', ''),
  ('lindalberto.filho@gran.com', 'Lindalberto Rufino Vales Campelo Filho', 'Engineering Manager', 'Manoel Roberto Aguirre de Almeida', 'manoel.almeida@gran.com', 'Preparatórios', 'Manoel Roberto Aguirre De Almeida'),
  ('luiz.araujo@gran.com', 'Luiz Inacio De Araujo Correa', 'TECH MANAGER', 'Manoel Roberto Aguirre de Almeida', 'manoel.almeida@gran.com', 'Payments', 'Manoel Roberto Aguirre De Almeida'),
  ('miller.horvath@gran.com', 'Miller Horvath', 'DATA MANAGER', 'Manoel Roberto Aguirre de Almeida', 'manoel.almeida@gran.com', 'Dados', 'Manoel Roberto Aguirre De Almeida'),
  ('rafael.caubit@gran.com', 'Rafael Jose Caubit de Carvalho', 'HEAD CYBER SECURITY', 'Manoel Roberto Aguirre de Almeida', 'manoel.almeida@gran.com', 'Cyber Security', 'Manoel Roberto Aguirre De Almeida'),
  ('raniery.ribeiro@gran.com', 'Raniery Regis Ribeiro', 'Engineering Manager', 'Manoel Roberto Aguirre de Almeida', 'manoel.almeida@gran.com', 'Growth', 'Manoel Roberto Aguirre De Almeida'),
  ('roger.pereira@gran.com', 'Roger Pereira', 'Devops Manager', 'Manoel Roberto Aguirre de Almeida', 'manoel.almeida@gran.com', 'DevOps', ''),
  ('carolina.ferla@gran.com', 'Carolina Russi Ferla', 'SOFTWARE ENGINEER I', 'Mayron Medeiros Gomes', 'mayron.gomes@gran.com', 'Ensino Superior', 'Mayron Medeiros Gomes'),
  ('eduardo.moura@gran.com', 'Eduardo Daniel De Moura', 'DESENVOLVEDOR FULLSTACK PL', 'Mayron Medeiros Gomes', 'mayron.gomes@gran.com', 'Ensino Superior', 'Valtemir Souza De Franca'),
  ('juliano.buzanello@gran.com', 'Juliano	Buzanello', 'SOFTWARE ENGINEER III', 'Mayron Medeiros Gomes', 'mayron.gomes@gran.com', 'Ensino Superior', 'Mayron Medeiros Gomes'),
  ('lemuel.teixeira@gran.com', 'Lemuel Rodrigues Teixeira', 'SOFTWARE ENGINEER III', 'Mayron Medeiros Gomes', 'mayron.gomes@gran.com', 'Ensino Superior', 'Valtemir Souza De Franca'),
  ('marcos.santos@gran.com', 'Marcos De Oliveira Goncalves Santos', 'SOFTWARE ENGINEER III', 'Mayron Medeiros Gomes', 'mayron.gomes@gran.com', 'Ensino Superior', 'Valtemir Souza De Franca'),
  ('marcos.pereira@gran.com', 'Marcos Moraes Pereira', 'SOFTWARE ENGINEER II', 'Mayron Medeiros Gomes', 'mayron.gomes@gran.com', 'Ensino Superior', 'Mayron Medeiros Gomes'),
  ('maycon.moreira@gran.com', 'Maycon da Silva Moreira', 'SOFTWARE ENGINEER III', 'Mayron Medeiros Gomes', 'mayron.gomes@gran.com', 'Ensino Superior', 'Mayron Medeiros Gomes'),
  ('pedro.ferreira@gran.com', 'Pedro Henrique Machado Ferreira', 'SOFTWARE ENGINEER II', 'Mayron Medeiros Gomes', 'mayron.gomes@gran.com', 'Ensino Superior', 'Mayron Medeiros Gomes'),
  ('andre.pereira@gran.com', 'Andre Luiz Pereira Silva', 'Assistente de Segurança da Informação', 'Melke Assis', 'melke.assis@gran.com', 'Cyber Security', 'Melke Alves De Assis'),
  ('danylo.gomes@gran.com', 'Danylo Alexandre Gomes', 'ESTAGIARIO', 'Melke Assis', 'melke.assis@gran.com', 'Cyber Security', 'Melke Alves De Assis'),
  ('mendelson.souza@gran.com', 'Mendelson Dumiense De Souza', '1', 'Melke Assis', 'melke.assis@gran.com', 'Cyber Security', 'Melke Alves De Assis'),
  ('airton.sousa@gran.com', 'Airton Chagas De Sousa', 'Engenheiro Dados Pl', 'Miller Horvath', 'miller.horvath@gran.com', 'Dados', 'Marcone Viana Peres'),
  ('bruno.santana@gran.com', 'Bruno Lima De Santana', 'DATA ENGINEER I', 'Miller Horvath', 'miller.horvath@gran.com', 'Dados', 'Marcone Viana Peres'),
  ('douglas.rodrigues@gran.com', 'Douglas Gontijo Rodrigues', 'STAFF DATA ANALYST', 'Miller Horvath', 'miller.horvath@gran.com', 'Dados', 'Miller Horvath'),
  ('gabriel.abreu@gran.com', 'Gabriel Costa Abreu', 'TECH MANAGER', 'Miller Horvath', 'miller.horvath@gran.com', 'Dados', 'Miller Horvath'),
  ('rafael.goncalves@gran.com', 'Rafael Luiz Gonçalves Santos', 'Não informado no diretório', 'Miller Horvath', 'miller.horvath@gran.com', '', ''),
  ('rodger.freitas@gran.com', 'Rodger William Oliveira Teixeira de Freitas', 'STAFF DATA ENGINEER', 'Miller Horvath', 'miller.horvath@gran.com', 'Dados', 'Miller Horvath'),
  ('victor.dellazeri@gran.com', 'Victor Pereira Dellazeri', 'DATA ENGINEER I', 'Miller Horvath', 'miller.horvath@gran.com', 'Dados', 'Marcone Viana Peres'),
  ('gleyson.carvalho@gran.com', 'Gleyson da Silva Carvalho', 'IT SUPPORT SUPERVISOR', 'Rafael Jose Caubit de Carvalho', 'rafael.caubit@gran.com', 'Cyber Security', 'Melke Alves De Assis'),
  ('jakson@gran.com', 'Jakson Fernandes Alves', 'INFORMATION SECURITY ANALYST I', 'Rafael Jose Caubit de Carvalho', 'rafael.caubit@gran.com', 'Cyber Security', 'Everson Emiliano Saraiva'),
  ('melke.assis@gran.com', 'Melke Assis', 'Supervisor Segurança da Informação', 'Rafael Jose Caubit de Carvalho', 'rafael.caubit@gran.com', '', ''),
  ('nathaly.souza@gran.com', 'Nathaly Soliely Santana Souza', 'ANALISTA DE INFRAESTRUTURA DE REDES', 'Rafael Jose Caubit de Carvalho', 'rafael.caubit@gran.com', 'Cyber Security', 'Everson Emiliano Saraiva'),
  ('vitor.pinto@gran.com', 'Vitor Campos Ferreira Pinto', 'INFORMATION SECURITY ANALYST III', 'Rafael Jose Caubit de Carvalho', 'rafael.caubit@gran.com', 'Cyber Security', 'Rafael Jose Caubit De Carvalho'),
  ('ana.lima@gran.com', 'Ana Isabel Araujo Lima', 'ESTAGIARIO', 'Raniery Regis Ribeiro', 'raniery.ribeiro@gran.com', 'Growth', 'Raniery Regis Ribeiro'),
  ('barbara.cobo@gran.com', 'Barbara Gianvechio Cobo', 'ESTAGIARIO', 'Raniery Regis Ribeiro', 'raniery.ribeiro@gran.com', 'Growth', 'Raniery Regis Ribeiro'),
  ('diego.barbosa@gran.com', 'Diego De Melo Barbosa', 'TECH MANAGER', 'Raniery Regis Ribeiro', 'raniery.ribeiro@gran.com', 'Growth', 'Raniery Regis Ribeiro'),
  ('gabriela.rocha@gran.com', 'Gabriela Franca De Moura Rocha', 'ESTAGIARIO', 'Raniery Regis Ribeiro', 'raniery.ribeiro@gran.com', 'Growth', 'Raniery Regis Ribeiro'),
  ('ingrid.carvalho@gran.com', 'Ingrid Coelho Carvalho', 'ESTAGIARIO', 'Raniery Regis Ribeiro', 'raniery.ribeiro@gran.com', 'Growth', 'Raniery Regis Ribeiro'),
  ('mayron.gomes@gran.com', 'Mayron Medeiros Gomes', 'Coordenador Desenvolvimento Software', 'Raniery Regis Ribeiro', 'raniery.ribeiro@gran.com', 'Ensino Superior', 'Raniery Regis Ribeiro'),
  ('talita.alves@gran.com', 'Talita Ester Araujo Alves', 'ESTAGIARIO', 'Raniery Regis Ribeiro', 'raniery.ribeiro@gran.com', 'Growth', 'Raniery Regis Ribeiro'),
  ('valtemir.franca@gran.com', 'Valtemir Souza De Franca', 'TECH MANAGER', 'Raniery Regis Ribeiro', 'raniery.ribeiro@gran.com', 'Ensino Superior', 'Raniery Regis Ribeiro'),
  ('manoel.almeida@gran.com', 'Manoel Roberto Aguirre de Almeida', 'CTO', 'Rodrigo Calado', '', '', ''),
  ('allyni.costa@gran.com', 'Allyni Fabiola Cesar Costa', 'COORDENADOR INFRAESTRUTURA DADOS', 'Roger Pereira', 'roger.pereira@gran.com', 'DevOps', 'Roger Luiz Pereira'),
  ('dionitas.santos@gran.com', 'Dionitas Mendes Dos Santos', 'STAFF CLOUD ENGINEER', 'Roger Pereira', 'roger.pereira@gran.com', 'DevOps', 'Roger Luiz Pereira'),
  ('henrique.repulho@gran.com', 'Henrique Lages Repulho', 'ENTERPRISE ARCHITECT TECH MANAGER', 'Roger Pereira', 'roger.pereira@gran.com', 'DevOps', 'Roger Luiz Pereira'),
  ('cassio.takarada@gran.com', 'Cassio Silva Takarada', 'SOFTWARE ENGINEER II', 'Valtemir Souza De Franca', 'valtemir.franca@gran.com', 'Growth', 'Bruno Henrique Trindade'),
  ('daniel.soares@gran.com', 'Daniel Pontes Freitas Soares', 'SRE III', 'Valtemir Souza De Franca', 'valtemir.franca@gran.com', 'DevOps', 'Murilo Augusto Peres'),
  ('edson.pimenta@gran.com', 'Edson Roberto De Souza Pimenta', 'SOFTWARE ENGINEER I', 'Valtemir Souza De Franca', 'valtemir.franca@gran.com', 'Growth', 'Bruno Henrique Trindade'),
  ('flavio.cunha@gran.com', 'Flavio Valle Da Cunha', 'DESENVOLVEDOR FULLSTACK JR', 'Valtemir Souza De Franca', 'valtemir.franca@gran.com', 'Growth', 'Bruno Henrique Trindade'),
  ('karolina.braccialli@gran.com', 'Karolina Braccialli do Espirito Santo', 'SOFTWARE ENGINEER II', 'Valtemir Souza De Franca', 'valtemir.franca@gran.com', 'Backoffice', 'Fabiano Rodrigues Ugulino'),
  ('leonardo.valerio@gran.com', 'Leonardo Augusto Valerio', 'SOFTWARE ENGINEER ASSOCIATE', 'Valtemir Souza De Franca', 'valtemir.franca@gran.com', 'Growth', 'Bruno Henrique Trindade'),
  ('marcus.oliveira@gran.com', 'Marcus Vinicius Alves De Oliveira', 'SOFTWARE ENGINEER III', 'Valtemir Souza De Franca', 'valtemir.franca@gran.com', 'Growth', 'Bruno Henrique Trindade'),
  ('maria.peres@gran.com', 'Maria Emilia Castro Oliveira Peres', 'DESENVOLVEDOR FRONT-END JR', 'Valtemir Souza De Franca', 'valtemir.franca@gran.com', '', ''),
  ('breno.maini@gran.com', 'Breno Augusto Maini da Silva', 'Analista de AppSec Jr', 'Vitor Campos Ferreira Pinto', 'vitor.pinto@gran.com', 'Cyber Security', 'Rafael Jose Caubit De Carvalho');

-- Espelha em `organogram` para auth / user_roles (compatibilidade)
DELETE FROM organogram;

INSERT INTO organogram (email, level, name, department, manager_name, manager_email)
SELECT
  email,
  0 AS level,
  name,
  tribe AS department,
  leader_name AS manager_name,
  leader_email AS manager_email
FROM tech_organogram;

INSERT INTO app_metadata (key, value) VALUES ('tech_organogram_seed', '002')
ON CONFLICT(key) DO UPDATE SET value = excluded.value;
